### ISSUE TITLE
it says "Please run: python -m autogpt"

### ISSUE THREAD

**Issue by leexiaoyaoLab** [thecookingsenpai/autogpt-gui#10]
when press "Go", it says "Please run: python -m autogpt".

i have check the .script/main.py and there is the content:

```
  from colorama import Style, init
  
  # Initialize colorama
  init(autoreset=True)
  
  # Use the bold ANSI style
  print(
      f"""{Style.BRIGHT}Please run:
  python -m autogpt
  """
)
```
i think the lastest verison is not allowed the run the cmd by 

`let args_cmd = ['scripts/main.py']`

**Comment by GigaGene** [comment]
I have same problem and after I ran python -m autogpt,
I have another message like these:
C:\AI\Auto-GPT>python -m autogpt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\AI\Auto-GPT\autogpt\__main__.py", line 12, in <module>
    from autogpt import commands as cmd
  File "C:\AI\Auto-GPT\autogpt\commands.py", line 9, in <module>
    cfg = Config()
          ^^^^^^
NameError: name 'Config' is not defined

**Comment by kuangzhu81** [comment]
// REVIEW Run ../scripts/main.py and redirect all the output to a variable live in the GUI
    // Set up the command
    let cmd = 'python'
    let args_cmd = ['-m', 'autogpt']
    // let args_cmd = ['scripts/main.py']
